hello:
  amount: 12.5
  inner-prop:
    port: 10000
    server: 192.168.1.1
  isimler: 
  - osman
  - ali
  - veli
  kelime-sayilari:
    gulegule: 20
    merhaba: 10
    selam: 5
  language: 3
  server-map:
    server1:
      port: 9090
      server: 127.0.0.1
    server2:
      port: 9090
      server: 127.0.0.1
  test: test stringi
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
server:
  http2:
    enabled: true
  port: 9090
